server:
  port: 8085

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ArjunSinghShekhawat/Microservice-Config
          clone-on-start: true
          default-label: main